name: CI

on: [push, pull_request]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check commit messages
        uses: webiny/action-conventional-commits@v1.3.0

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: cargo test --all-features

      - name: format
        run: cargo fmt --check

      - name: clippy
        run: cargo clippy --all-features -- -D warnings

      - name: rustdoc
        run: cargo doc --workspace --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings
